export enum DemandeCombatStatusEnum {
  DEMANDE_ENVOYEE = "DEMANDE_ENVOYEE",
  DEMANDE_RECUE = "DEMANDE_RECUE",
  DEMANDE_ACCEPTEE = "DEMANDE_ACCEPTEE",
  PARTIE_CREEE = "PARTIE_CREEE",
  DEMANDE_REFUSEE = "DEMANDE_REFUSEE",
  DEMANDE_CLOSE = "DEMANDE_CLOSE"
}
